[book]
authors = ["The Managarm Project"]
language = "en"
multilingual = false
src = "src"
title = "libasync documentation"

[output.html]
site-url = "/libasync/"
git-repository-url = "https://github.com/managarm/libasync"
mathjax-support = true

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
