name: Tests and coverage
on:
  push:
  pull_request:

permissions:
  statuses: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Get dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive \
              apt-get -y install ninja-build build-essential \
                             git libgtest-dev
          pipx install meson
          pipx install gcovr
      - name: Build
        run: |
          git clone --depth=1 https://github.com/managarm/frigg.git subprojects/frigg
          meson setup --buildtype=debug -Dbuild_tests=true -Db_coverage=true build
          cd build
          ninja test
          ninja coverage-html
          ninja coverage-xml
          ninja coverage-text
          ninja coverage-sonarqube
      - name: Upload coverage reports as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: coverages
          path: |
            build/meson-logs/coverage.xml
            build/meson-logs/sonarqube.xml
            build/meson-logs/coverage.txt
            build/meson-logs/coveragereport/
